fix: media info size

diff --git a/.local/bin/media-info b/.local/bin/media-info
--- a/.local/bin/media-info
+++ b/.local/bin/media-info
@@ -1,10 +1,22 @@
 #!/bin/bash
 
-max_length=30
+max_length=25
 delay=0.5
 scroll_speed=1
 
-prefix="   "
+while getopts "l:" opt; do
+  case $opt in
+    l)
+      max_length="$OPTARG"
+      ;;
+    \?)
+      echo "Invalid option: -$OPTARG" >&2
+      exit 1
+      ;;
+  esac
+done
+
+prefix="  "
 prefix_len=${#prefix}
 scroll_len=$((max_length - prefix_len))
 
